### ISSUE TITLE
메뉴얼 읽기

### ISSUE THREAD

**Issue by Tastypotato245** [Tastypotato245/minishell#2]
## 이전 작업
#3 

## 내용
https://www.gnu.org/software/bash/manual/bash.html

**Comment by cho0h5** [comment]
각자 분야에 필요한 부분을 중점적으로 요약하기

**Comment by cho0h5** [comment]
노션에 3장까지 정리 완료했습니다~

**Comment by Tastypotato245** [comment]
정리한 것 읽었습니당

**Comment by Tastypotato245** [comment]
기초적인 구조는 나왔고, 처리 순서 관련해서 더 알아봐야한다면 새로운 이슈 할당하겠습니다. 닫겠습니다.
